import path from 'node:path';
import { promises as fs } from 'node:fs';
import archiver from 'archiver';
import { getProjectDir, readJson, listFrames } from '@/lib/cache';
import type { Scene, SiteStructure } from '@/features/pipeline/types';

const TEMPLATE_DIR = path.resolve(process.cwd(), 'templates', 'next-export');

/**
 * Bundle an exportable Next.js project for the given project and stream it to
 * the provided writable output. Template files are substituted with
 * project-specific content (site copy, palette). Frames are copied into
 * public/frames.
 */
export async function bundleExport(args: {
  projectId: string;
  output: NodeJS.WritableStream;
}): Promise<void> {
  const site = await readJson<SiteStructure>(args.projectId, 'site.json');
  const scene = await readJson<Scene>(args.projectId, 'scene.json');
  if (!site || !scene) {
    throw new Error('Project not ready for export — site.json or scene.json missing');
  }
  const frames = await listFrames(args.projectId);
  if (frames.length === 0) {
    throw new Error('Project has no frames yet');
  }
  const projectDir = getProjectDir(args.projectId);

  const archive = archiver('zip', { zlib: { level: 9 } });
  archive.pipe(args.output);

  // 1. Copy all non-templated files verbatim from the template
  const staticFiles = [
    'tsconfig.json',
    'tailwind.config.ts',
    'postcss.config.mjs',
    'next.config.mjs',
    'next-env.d.ts',
    'vercel.json',
    'app/globals.css',
    'app/layout.tsx',
    // Core components
    'components/HeroFlipbook.tsx',
    'components/Section.tsx',
    'components/motion.tsx',
    'components/SmoothScroll.tsx',
    // shadcn/ui primitives
    'components/ui/accordion.tsx',
    'components/ui/badge.tsx',
    'components/ui/button.tsx',
    'components/ui/card.tsx',
    'components/ui/separator.tsx',
    // Lib
    'lib/utils.ts',
  ];
  for (const rel of staticFiles) {
    const abs = path.join(TEMPLATE_DIR, rel);
    if (await exists(abs)) {
      archive.file(abs, { name: rel });
    }
  }

  // 2. Templated files (token substitution)
  const pkgJson = await renderPackageJson(site.brandName);
  archive.append(pkgJson, { name: 'package.json' });

  const pageTsx = await renderPageTsx({ site, frameCount: frames.length, scene });
  archive.append(pageTsx, { name: 'app/page.tsx' });

  const readme = renderReadme(site);
  archive.append(readme, { name: 'README.md' });

  // 3. Keyframe → public/keyframe.png (sharp 1536×1024 hero image)
  const keyframePath = path.join(projectDir, 'keyframe.png');
  if (await exists(keyframePath)) {
    archive.file(keyframePath, { name: 'public/keyframe.png' });
  }

  // 4. Frames → public/frames/ (only if the video model video was enabled)
  for (const frame of frames) {
    archive.file(path.join(projectDir, 'frames', frame), {
      name: `public/frames/${frame}`,
    });
  }

  await archive.finalize();
}

async function exists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

async function renderPackageJson(brandName: string): Promise<string> {
  const slug = brandName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '') || 'sitesculpt-export';
  const template = await fs.readFile(path.join(TEMPLATE_DIR, 'package.json'), 'utf8');
  return template.replace(/__NAME__/g, slug);
}

async function renderPageTsx(args: {
  site: SiteStructure;
  frameCount: number;
  scene: Scene;
}): Promise<string> {
  const template = await fs.readFile(path.join(TEMPLATE_DIR, 'app', 'page.tsx'), 'utf8');
  const siteJson = JSON.stringify(args.site, null, 2);
  const paletteJson = JSON.stringify(args.scene.palette, null, 2);
  // Default to balanced if expandPrompt didn't emit a style block (older
  // generations or legacy briefs). The renderer falls back to balanced too.
  const styleJson = JSON.stringify(
    args.scene.style ?? {
      heroLayout: 'centered',
      typography: 'editorial',
      accentUsage: 'text',
      density: 'balanced',
    },
    null,
    2,
  );
  return template
    .replace(/__SITE_JSON__/g, siteJson)
    .replace(/__PALETTE_JSON__/g, paletteJson)
    .replace(/__STYLE_JSON__/g, styleJson)
    .replace(/__FRAME_COUNT__/g, String(args.frameCount));
}

function renderReadme(site: SiteStructure): string {
  return `# ${site.brandName}

Generated by [sitesculpt](https://github.com/).

## Run locally

\`\`\`bash
npm install
npm run dev
\`\`\`

Open http://localhost:3000.

## Deploy to Vercel

Click the button, import this folder, done.

[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new)

## Customize

- **Copy** lives in \`app/page.tsx\` (the \`site\` object at the top)
- **Frames** are in \`public/frames/\` — drop in new ones with the same naming scheme
- **Colors** are in \`app/page.tsx\` (the \`palette\` object)

Everything else is yours.
`;
}
