// Template compositor config — drives the HTML overlay rendered at
// /template-render/[id]. Each entry specifies the background prompt
// (AI-generated) AND the HTML overlay content (nav + headline + CTAs).

export interface TemplateConfig {
  id: string;
  brandName: string;
  logoIcon?: string; // lucide icon name or initial
  nav: string[];
  navCta: string;
  headline: string;
  headlineAccent?: string; // word(s) inside headline to highlight with gradient
  subtext: string;
  primaryCta: string;
  secondaryCta?: string;
  smallLabel?: string; // "FROM $48 · FREE SHIPPING" style
  stats?: Array<{ value: string; label: string }>;
  theme: 'dark' | 'light' | 'cream';
  accentColor: string; // hex
  headlineFont: 'sans' | 'serif' | 'display';
  layout: 'centered' | 'split-left' | 'split-right';
  /** The AI background prompt — no UI/text/logos in scene */
  bgPrompt: string;
}

export const TEMPLATE_CONFIGS: TemplateConfig[] = [
  {
    id: 'saas-landing',
    brandName: 'StackForge',
    logoIcon: 'zap',
    nav: ['Docs', 'SDK', 'Community', 'Pricing'],
    navCta: 'Start Building',
    headline: 'Build Faster. Ship Smarter.',
    subtext: 'A powerful infrastructure platform for developers building modern applications.',
    primaryCta: 'Start Building for Free',
    theme: 'dark',
    accentColor: '#22d3ee',
    headlineFont: 'display',
    layout: 'centered',
    bgPrompt: 'Ultra-clean composition, premium color grading, full-bleed website hero background. Dark navy digital grid landscape stretching to horizon, glowing cyan wireframe lines and light trails, floating translucent holographic terminal windows with code silhouettes, geometric 3D nodes, subtle particle effects, atmospheric depth fog. Cinematic tech aesthetic with purple violet accents. No text, no logos, no watermarks in-frame. Aspect ratio 16:9.',
  },
  {
    id: 'creative-agency',
    brandName: 'OrbitCRM',
    nav: ['Features', 'Integrations', 'Pricing', 'Docs'],
    navCta: 'Start Free Trial',
    headline: 'Run Your Agency Smarter.',
    headlineAccent: 'Smarter.',
    subtext: 'All your projects, clients, analytics and invoices — unified into one powerful platform.',
    primaryCta: 'Try it Free for 14 Days',
    theme: 'light',
    accentColor: '#3b82f6',
    headlineFont: 'display',
    layout: 'centered',
    bgPrompt: 'Ultra-clean composition, premium color grading, full-bleed website hero background. Hand-painted soft pastel countryside landscape with rolling green hills, warm soft sunlight streaming through clouds, birds flying in distance, gentle wildflowers in foreground, dreamy impressionist painting style. No text, no logos, no watermarks in-frame. Aspect ratio 16:9.',
  },
  {
    id: 'app-landing',
    brandName: 'TripVault',
    nav: ['Features', 'Pricing', 'Company', 'Help'],
    navCta: 'Sign In',
    headline: 'All Your Travel Plans. One Simple Place.',
    subtext: 'Store tickets, itineraries, bookings and documents — automatically organized for every trip.',
    primaryCta: 'Download App',
    theme: 'light',
    accentColor: '#60a5fa',
    headlineFont: 'sans',
    layout: 'centered',
    bgPrompt: 'Ultra-clean composition, premium color grading, full-bleed website hero background. Bright sky blue gradient with soft fluffy white clouds drifting, subtle sun rays, dreamy atmospheric travel aesthetic, playful soft gradients, minimal composition. No UI elements, no text, no logos, no watermarks in-frame. Aspect ratio 16:9.',
  },
  {
    id: 'ecommerce-brand',
    brandName: 'Maison',
    nav: ['Shop', 'Collection', 'Journal', 'About'],
    navCta: 'Cart',
    headline: 'Essentials. Nothing more.',
    headlineAccent: 'more.',
    subtext: 'Thoughtfully designed everyday objects made from sustainable materials and minimal packaging.',
    primaryCta: 'Shop the Collection',
    secondaryCta: 'Our Story',
    smallLabel: 'FROM $48 · FREE SHIPPING',
    theme: 'cream',
    accentColor: '#8b6f47',
    headlineFont: 'serif',
    layout: 'split-left',
    bgPrompt: 'Ultra-clean composition, premium color grading, full-bleed website hero background. Minimalist editorial product still life with artisan ceramic vase, handblown amber glass bottle, folded natural linen textile draped over warm cream stone pedestal, small potted succulent, soft natural window light casting gentle elongated shadows. Apple-style minimal product photography with generous whitespace. Warm cream cream tones. No text, no logos, no watermarks in-frame. Aspect ratio 16:9.',
  },
  {
    id: 'restaurant',
    brandName: 'Ember & Vine',
    nav: ['Menu', 'Reservations', 'Wine', 'Events', 'About'],
    navCta: 'Book a Table',
    headline: 'Where the season comes to the table.',
    subtext: 'An intimate 14-seat tasting menu rooted in what the land provides, paired with a natural wine program.',
    primaryCta: 'Reserve Your Evening',
    secondaryCta: 'View Menu',
    smallLabel: 'OPEN WED–SUN · 6PM–11PM · BROOKLYN NY',
    theme: 'dark',
    accentColor: '#d4a574',
    headlineFont: 'serif',
    layout: 'centered',
    bgPrompt: 'Ultra-clean composition, premium color grading, full-bleed website hero background. Dramatic overhead photograph of an artfully plated seasonal tasting course on handmade ceramic plate with microgreens, edible flowers, sauce swoops, seared protein, warm ambient candlelight, dark walnut wood surface, wine glass edge visible, linen napkin, copper cutlery. Luxury Michelin editorial with moody atmospheric lighting. No text, no logos, no watermarks in-frame. Aspect ratio 16:9.',
  },
  {
    id: 'portfolio',
    brandName: 'Miles Kaplan',
    nav: ['Work', 'About', 'Journal', 'Contact'],
    navCta: 'Available Q2',
    headline: 'Design that earns its place on the page.',
    headlineAccent: 'earns its place',
    subtext: 'Working with early-stage startups on brand identity, type systems, and digital products.',
    primaryCta: 'View Selected Work',
    secondaryCta: 'Read the Journal',
    smallLabel: 'NOTION · LINEAR · ARC · FIGMA · RAMP · VERCEL',
    theme: 'cream',
    accentColor: '#5a7db8',
    headlineFont: 'serif',
    layout: 'split-left',
    bgPrompt: 'Ultra-clean composition, premium color grading, full-bleed website hero background. Overhead editorial flat-lay of designer workspace — open leather sketchbook with logo sketches in pencil, color palette swatches fanned out, vintage typography specimen book, brass ruler, espresso cup with latte art, small plant, on warm raw concrete desk with soft natural window light. Swiss minimal editorial aesthetic with generous whitespace. No text, no logos, no watermarks in-frame. Aspect ratio 16:9.',
  },
  {
    id: 'startup-launch',
    brandName: 'Nexus',
    nav: ['Docs', 'Changelog', 'Discord', 'Pricing'],
    navCta: 'Join Waitlist',
    headline: 'Dev tools. Rebuilt from first principles.',
    subtext: 'The next-generation toolkit for developers who refuse to accept slow. Open-source core, premium cloud.',
    primaryCta: 'Claim Early Access',
    secondaryCta: 'See the Demo',
    smallLabel: 'BACKED BY Y COMBINATOR · USED AT STRIPE, FIGMA, LINEAR',
    theme: 'dark',
    accentColor: '#8b5cf6',
    headlineFont: 'sans',
    layout: 'centered',
    bgPrompt: 'Ultra-clean composition, premium color grading, full-bleed website hero background. Deep dark purple cosmic scene with floating translucent 3D crystal prisms and geometric polyhedra, volumetric violet and cyan light beams slicing through space, subtle particle nebula effect, soft lens flare in upper right. Bold sci-fi aesthetic with dramatic volumetric lighting. No text, no logos, no watermarks in-frame. Aspect ratio 16:9.',
  },
  {
    id: 'nonprofit',
    brandName: 'Blue Horizon',
    nav: ['Mission', 'Programs', 'Impact', 'Team', 'Stories'],
    navCta: 'Donate Now',
    headline: 'The ocean needs a few good humans.',
    headlineAccent: 'good humans.',
    subtext: 'Coastal cleanup programs and marine protection advocacy across three continents.',
    primaryCta: 'Get Involved',
    secondaryCta: 'View Our Impact',
    stats: [
      { value: '2.4M lbs', label: 'Plastic removed' },
      { value: '127', label: 'Beaches restored' },
      { value: '40+', label: 'Partner orgs' },
      { value: '18K', label: 'Volunteers' },
    ],
    theme: 'dark',
    accentColor: '#f59e0b',
    headlineFont: 'serif',
    layout: 'centered',
    bgPrompt: 'Ultra-clean composition, premium color grading, full-bleed website hero background. Breathtaking aerial drone photograph from high altitude of crystal clear turquoise Caribbean ocean meeting pristine white sand coastline, visible coral reef formations through transparent water, dramatic golden hour sunlight creating long light rays on gentle waves, small coastal rocks. Environmental documentary cinematography. No text, no logos, no watermarks in-frame. Aspect ratio 16:9.',
  },
  {
    id: 'ai-platform',
    brandName: 'Aura',
    nav: ['Overview', 'Infrastructure', 'Agents', 'Scale', 'Deploy'],
    navCta: 'Deploy Now',
    headline: 'The intelligence layer for modern enterprise.',
    subtext: 'Unify your fragmented data streams. Aura processes billions of events in real-time.',
    primaryCta: 'Request Access',
    secondaryCta: 'Explore Architecture',
    theme: 'dark',
    accentColor: '#34d399',
    headlineFont: 'sans',
    layout: 'centered',
    bgPrompt: 'Ultra-clean composition, premium color grading, full-bleed website hero background. Breathtaking cinematic 3D render of floating sky islands connected by cascading waterfalls disappearing into soft clouds below, snow-capped mountains in distance, dramatic volumetric god rays piercing atmospheric mist, Unreal Engine quality Ghibli-meets-Inception aesthetic with epic scale and depth. No text, no logos, no watermarks in-frame. Aspect ratio 16:9.',
  },
  {
    id: 'space-research',
    brandName: 'UNVRS Labs',
    nav: ['Premium', 'Scroll', 'Research', 'Missions', 'Gallery'],
    navCta: 'Start Building',
    headline: 'Chart the unknown.',
    subtext: 'Advanced deep-space research platform for the next generation of cosmic explorers.',
    primaryCta: 'Enter the Lab',
    secondaryCta: 'View Missions',
    theme: 'dark',
    accentColor: '#a78bfa',
    headlineFont: 'display',
    layout: 'centered',
    bgPrompt: 'Ultra-clean composition, premium color grading, full-bleed website hero background. Stunning cinematic 3D space scene with massive glowing ring portal in center with violet and cyan energy, floating Saturn-like ringed planets in foreground, distant nebulae and galaxies, stars scattered, small spacecraft silhouette for scale, volumetric cosmic light. Deep dark purple background, Interstellar meets No Mans Sky aesthetic. No text, no logos, no watermarks in-frame. Aspect ratio 16:9.',
  },
  {
    id: 'architecture',
    brandName: 'Meridian',
    nav: ['Projects', 'Practice', 'Awards', 'Journal', 'Contact'],
    navCta: 'Commission',
    headline: 'Where vision meets form.',
    headlineAccent: 'form.',
    subtext: 'A contemporary architecture practice designing residences, cultural institutions, and urban landmarks.',
    primaryCta: 'View Portfolio',
    secondaryCta: 'About Our Practice',
    theme: 'dark',
    accentColor: '#e8b874',
    headlineFont: 'serif',
    layout: 'centered',
    bgPrompt: 'Ultra-clean composition, premium color grading, full-bleed website hero background. Cinematic 3D architectural visualization of a minimalist modernist building with glass walls and exposed concrete perched on a cliff overlooking ocean at golden hour, dramatic volumetric sunlight streaming horizontally, native coastal landscaping, long shadows, photoreal Unreal Engine render quality. Sophisticated architectural photography with cinematic warm lighting. No text, no logos, no watermarks in-frame. Aspect ratio 16:9.',
  },
  {
    id: 'creative-3d',
    brandName: 'PRISM',
    nav: ['Work', 'Services', 'About', 'Contact'],
    navCta: 'Start a Project',
    headline: 'Design at the speed of imagination.',
    subtext: 'We craft brand worlds, immersive digital experiences, and cinematic interactive identity systems.',
    primaryCta: 'View Our Work',
    secondaryCta: 'Our Process',
    theme: 'dark',
    accentColor: '#ff6ec7',
    headlineFont: 'sans',
    layout: 'centered',
    bgPrompt: 'Ultra-clean composition, premium color grading, full-bleed website hero background. Stunning cinematic 3D abstract scene with floating translucent glass prisms catching rainbow light dispersions, liquid chrome spheres reflecting a warm sunset sky with pink and orange tones, iridescent metallic ribbons flowing through space, volumetric lighting, ultra-high-detail Octane render quality. Bold cinematic 3D concept art. No text, no logos, no watermarks in-frame. Aspect ratio 16:9.',
  },
];
