'use client';

import type { CSSProperties } from 'react';
import { ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Section } from '@/components/Section';
import { HeroFlipbook } from '@/components/HeroFlipbook';
import { SmoothScroll } from '@/components/SmoothScroll';
import { HeroParallax, Reveal } from '@/components/motion';

// ─── Generated by sitesculpt — edit freely ──────────────────────────────────
const site = __SITE_JSON__ as const;
const palette = __PALETTE_JSON__ as const;
const style = __STYLE_JSON__ as {
  heroLayout: 'bottom-left' | 'centered' | 'split';
  typography: 'editorial' | 'geometric' | 'expressive';
  accentUsage: 'text' | 'backgrounds' | 'borders';
  density: 'spacious' | 'balanced' | 'compact';
};
const FRAME_COUNT = __FRAME_COUNT__;
// ────────────────────────────────────────────────────────────────────────────

export default function Page() {
  // Section vertical padding scales with the brief's density token.
  const densityVars: Record<string, string> =
    style.density === 'spacious'
      ? { '--sec-y-sm': '8rem', '--sec-y-md': '11rem' }
      : style.density === 'compact'
        ? { '--sec-y-sm': '4rem', '--sec-y-md': '6rem' }
        : { '--sec-y-sm': '6rem', '--sec-y-md': '8rem' };

  // Override shadcn design tokens from the generated scene palette
  const tokens: CSSProperties = {
    '--color-background': palette.background,
    '--color-foreground': palette.foreground,
    '--color-card': `color-mix(in oklab, ${palette.foreground} 4%, ${palette.background})`,
    '--color-card-foreground': palette.foreground,
    '--color-primary': palette.accent,
    '--color-primary-foreground': palette.background,
    '--color-secondary': `color-mix(in oklab, ${palette.foreground} 8%, ${palette.background})`,
    '--color-secondary-foreground': palette.foreground,
    '--color-muted': `color-mix(in oklab, ${palette.foreground} 6%, ${palette.background})`,
    '--color-muted-foreground': `color-mix(in oklab, ${palette.foreground} 60%, transparent)`,
    '--color-input': `color-mix(in oklab, ${palette.foreground} 12%, transparent)`,
    '--color-ring': palette.accent,
    '--color-border': `color-mix(in oklab, ${palette.foreground} 10%, transparent)`,
    ...densityVars,
    backgroundColor: palette.background,
    color: palette.foreground,
  } as CSSProperties;

  return (
    <SmoothScroll>
      <main style={tokens} className="min-h-screen font-sans antialiased">
        {/* Top nav */}
        <nav className="absolute inset-x-0 top-0 z-30 mx-auto flex max-w-6xl items-center justify-between px-6 py-7 md:px-12">
          <span className="font-mono text-[11px] uppercase tracking-[0.22em] text-foreground/95">
            {site.brandName}
          </span>
          <div className="hidden items-center gap-8 text-xs text-foreground/70 md:flex">
            {(site.sections as readonly { title: string }[]).slice(0, 4).map((s, i) => (
              <a key={i} href={`#section-${i}`} className="transition hover:text-foreground">
                {s.title.split(/[.,—]/)[0]?.trim().slice(0, 20)}
              </a>
            ))}
          </div>
        </nav>

        {/* Hero — keyframe with Ken Burns (sharp 1536×1024) by default.
             If frames exist (the video model video was enabled), use the flipbook instead. */}
        {FRAME_COUNT > 0 ? (
          <HeroFlipbook
            frameCount={FRAME_COUNT}
            backgroundColor={palette.background}
          >
            <HeroOverlay />
          </HeroFlipbook>
        ) : (
          <div className="relative h-screen w-full overflow-hidden">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src="/keyframe.png"
              alt=""
              aria-hidden="true"
              className="absolute inset-0 h-full w-full object-cover"
              style={{
                animation: 'kenBurns 30s ease-in-out infinite alternate',
                transformOrigin: 'center center',
              }}
            />
            <HeroOverlay />
          </div>
        )}

        {/* Sections — with visual zone treatments for variety */}
        {(site.sections as readonly { layout: string; label?: string; variant?: 'default' | 'alt'; title: string; body: string; cta?: string; items?: readonly Record<string, unknown>[] }[]).map((section, i) => {
          const zone = getZone(section.layout, i);
          return (
            <div key={i} id={`section-${i}`} className={zone.className} style={zone.style}>
              <Section
                layout={section.layout as Parameters<typeof Section>[0]['layout']}
                label={section.label}
                variant={section.variant}
                title={section.title}
                body={section.body}
                cta={section.cta}
                items={section.items as Parameters<typeof Section>[0]['items']}
              />
            </div>
          );
        })}

        {/* Footer */}
        <footer className="border-t border-border">
          <div className="mx-auto flex max-w-6xl items-baseline justify-between px-6 py-12 md:px-12">
            <div className="font-serif text-2xl italic text-foreground/90">{site.brandName}</div>
            <div className="font-mono text-[10px] uppercase tracking-[0.2em] text-muted-foreground">
              © {new Date().getFullYear()}
            </div>
          </div>
        </footer>
      </main>
    </SmoothScroll>
  );
}

function HeroOverlay() {
  return (
    <div className="pointer-events-none absolute inset-0 mx-auto flex max-w-6xl flex-col justify-end px-6 pb-24 md:px-12 md:pb-32">
      <div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-background/80 via-background/20 to-transparent" />
      <HeroParallax className="pointer-events-auto relative max-w-3xl">
        {/* Eyebrow */}
        <div className="mb-6 flex items-center gap-3 font-mono text-[10px] uppercase tracking-[0.25em] text-foreground/70">
          <span className="inline-block h-px w-8 bg-foreground/40" />
          <span>
            {(site.hero.subheadline as string).split(/[.—,]/)[0]?.trim().toLowerCase().slice(0, 42)}
          </span>
        </div>

        {/* Headline */}
        <h1
          className="font-serif text-5xl leading-[0.92] tracking-[-0.025em] text-foreground sm:text-7xl md:text-8xl"
          style={{ textShadow: '0 2px 60px rgba(0,0,0,0.5)' }}
        >
          {renderHeadline(site.hero.headline as string)}
        </h1>

        {/* Subheadline */}
        <p
          className="mt-6 max-w-xl text-base leading-relaxed text-foreground/85 md:text-lg"
          style={{ textShadow: '0 2px 20px rgba(0,0,0,0.5)' }}
        >
          {site.hero.subheadline}
        </p>

        {/* CTA */}
        <div className="mt-10 flex flex-wrap items-center gap-6">
          <Button size="lg" className="rounded-full px-7 transition-transform hover:scale-105">
            {site.hero.ctaPrimary}
            <ArrowRight className="size-4" />
          </Button>
          {site.hero.ctaSecondary ? (
            <a href="#section-0" className="text-sm text-foreground/80 transition hover:translate-x-1 hover:text-foreground">
              {site.hero.ctaSecondary} →
            </a>
          ) : null}
        </div>
      </HeroParallax>
    </div>
  );
}

function renderHeadline(headline: string): React.ReactNode {
  const parts = headline.split(/(?<=\.)\s/);
  if (parts.length >= 2) {
    const last = parts[parts.length - 1] ?? '';
    const rest = parts.slice(0, -1).join(' ');
    return (
      <>
        {rest}{' '}
        <em className="italic opacity-95">{last}</em>
      </>
    );
  }
  return headline;
}

// Visual zone system — breaks monotony of same-background sections
function getZone(
  layout: string,
  index: number,
): { className: string; style?: React.CSSProperties } {
  if (layout === 'cta') {
    return {
      className: 'relative overflow-hidden',
      style: {
        background:
          `linear-gradient(135deg, ${palette.accent}, color-mix(in oklab, ${palette.accent} 70%, ${palette.background}))`,
        '--color-foreground': `${palette.background}`,
        '--color-background': `${palette.accent}`,
        '--color-muted-foreground': `color-mix(in oklab, ${palette.background} 70%, transparent)`,
        '--color-border': `color-mix(in oklab, ${palette.background} 20%, transparent)`,
      } as React.CSSProperties,
    };
  }
  if (layout === 'stat-grid' || layout === 'pricing-tiers' || layout === 'testimonial-wall') {
    return {
      className: 'relative',
      style: {
        background: `color-mix(in oklab, ${palette.foreground} 3%, ${palette.background})`,
      },
    };
  }
  if (layout === 'quote') {
    return {
      className: 'relative',
      style: {
        background: `color-mix(in oklab, ${palette.accent} 5%, ${palette.background})`,
      },
    };
  }
  if (layout === 'logo-strip') {
    return { className: '' };
  }
  if (index % 3 === 2) {
    return {
      className: 'relative',
      style: {
        background: `color-mix(in oklab, ${palette.foreground} 2%, ${palette.background})`,
      },
    };
  }
  return { className: '' };
}
